name: Build WONDERFULAND

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install PyQt5
        pip install minecraft-launcher-lib
        pip install requests
        pip install Pillow
        pip install psutil

    - name: Build EXE
      run: |
        pyinstaller main.py ^
        --name WONDERFULAND ^
        --onefile ^
        --noconsole ^
        --clean ^
        --collect-all minecraft_launcher_lib ^
        --collect-all PyQt5 ^
        --collect-all requests ^
        --collect-all PIL ^
        --collect-all psutil ^
        --hidden-import pkg_resources.py2_warn ^
        --hidden-import pkg_resources.markers ^
        --hidden-import pkg_resources.extern ^
        --hidden-import pkg_resources.extern.packaging ^
        --hidden-import pkg_resources.extern.pyparsing

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WONDERFULAND_BUILD
        path: dist/WONDERFULAND.exe

    - name: Publish Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-build
        name: WONDERFULAND Auto Build
        files: dist/WONDERFULAND.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
